version: '3'

services:
  tunnel:
    image: wernight/ngrok
    container_name: ngrok
    ports:
      - "4040:4040"
    command: ngrok http -log stdout --authtoken $NGROK_AUTHTOKEN app:5000

  app:
    container_name: app
    volumes:
      - .:/app
    build:
      context: .
    ports:
      - "5000:5000"